package com.applaunch.bgm.utils

object ApiConstants {
        const val LOGIN ="auth/device-auth/login"
        const val CONTACT_SUPPORT ="settings/contact-support"
        const val CONTACT_FORM ="settings/contact/send-feedback"
        const val HOME ="home/thumbnail"
        const val COLLECTION ="collection/list"
        const val CREATE_COLLECTION ="collection/create"
        const val PAGE = "page"
        const val LIMIT = "limit"
        const val MEET ="media/all-thumbnails/{page}/{limit}"
        const val ARTICLE_ID ="id"
        const val ARTICLE ="media/article-details/{id}"
        const val FAVORITE_ID ="id"
        const val FAVORITE_ITEM ="favorite/all-collections/{id}"
        const val ALL_FAVORITE ="favorite/all-collections"
        const val EDIT_ID ="id"
        const val EDIT ="collection/modify/{id}"
        const val FAVORITE ="favorite/list"
        const val LIKE ="like-dislike"
        const val FAVORITE_SAVE ="favorite/save-remove"
        const val DELETE_ID ="id"
        const val DELETE_COLLECTION ="collection/drop/{id}"
        const val CHECK_CHALLENGE ="challenge/check-step-accept"
        const val ENTER_STEPS ="challenge/enter-steps"
        const val WEBINAR_ID ="id"
        const val WEBINAR ="media/webinar-details/{id}"
}